spring:
  datasource:
    url: jdbc:mysql://mydbinstance.cfsyp7ejcw4o.ap-northeast-2.rds.amazonaws.com:3306/honeyrock?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: honeyrock
    password: 12345678
    
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 20971520
      max-request-size: 41943040
      file-size-threshold: 20971520
      
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  
server:
  port: 80
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
